server:
  port: 1901
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/LuisF-1995/aquiles
          search-paths: config-services
  application:
    name: config-server
